# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08io.proto\"\x9e\x01\n\x0eRetransmission\x1a\x8b\x01\n\x07Request\x12\x11\n\ttensor_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12/\n\x04\x64\x61ta\x18\x63 \x03(\x0b\x32!.Retransmission.Request.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"d\n\nPacketLoss\x1a-\n\x07Request\x12\x11\n\ttensor_id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x1a\'\n\x08Response\x12\x1b\n\x13missing_packet_list\x18\x01 \x03(\x05\"@\n\x04Sync\x1a\x38\n\x12SendBarrierRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\ttensor_id\x18\x02 \x01(\x05\"\x06\n\x04Null2\xad\x01\n\nSwitchmlIO\x12.\n\x0bSendBarrier\x12\x18.Sync.SendBarrierRequest\x1a\x05.Null\x12\x30\n\x0eRetransmission\x12\x17.Retransmission.Request\x1a\x05.Null\x12=\n\x10ReadMissingSlice\x12\x13.PacketLoss.Request\x1a\x14.PacketLoss.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETRANSMISSION_REQUEST_DATAENTRY._options = None
  _RETRANSMISSION_REQUEST_DATAENTRY._serialized_options = b'8\001'
  _RETRANSMISSION._serialized_start=13
  _RETRANSMISSION._serialized_end=171
  _RETRANSMISSION_REQUEST._serialized_start=32
  _RETRANSMISSION_REQUEST._serialized_end=171
  _RETRANSMISSION_REQUEST_DATAENTRY._serialized_start=128
  _RETRANSMISSION_REQUEST_DATAENTRY._serialized_end=171
  _PACKETLOSS._serialized_start=173
  _PACKETLOSS._serialized_end=273
  _PACKETLOSS_REQUEST._serialized_start=32
  _PACKETLOSS_REQUEST._serialized_end=77
  _PACKETLOSS_RESPONSE._serialized_start=234
  _PACKETLOSS_RESPONSE._serialized_end=273
  _SYNC._serialized_start=275
  _SYNC._serialized_end=339
  _SYNC_SENDBARRIERREQUEST._serialized_start=283
  _SYNC_SENDBARRIERREQUEST._serialized_end=339
  _NULL._serialized_start=341
  _NULL._serialized_end=347
  _SWITCHMLIO._serialized_start=350
  _SWITCHMLIO._serialized_end=523
# @@protoc_insertion_point(module_scope)
